<script lang="ts">
	import './layout.css';
	import favicon from '$lib/assets/favicon.svg';
	import TopBar from '$lib/components/nav/TopBar.svelte';
	import MobileTabBar from '$lib/components/nav/MobileTabBar.svelte';
	import Footer from '$lib/components/nav/Footer.svelte';
	import { ENABLE_DEV_TOOLS } from '$lib/config/env';
	import { pwaInfo } from 'virtual:pwa-info';
	import type { Component } from 'svelte';
	import { page } from '$app/state';
	import { organizationJsonLd, websiteJsonLd } from '$lib/seo';

	const siteJsonLdBlocks = [organizationJsonLd(), websiteJsonLd()].map(
		(ld) =>
			// eslint-disable-next-line no-useless-escape -- el escape de "\/" es funcional: sin él, el texto de cierre de esta plantilla coincidiría literalmente con el del bloque <script> real de este archivo y Svelte lo cerraría ahí mismo.
			`<script type="application/ld+json">${JSON.stringify(ld).replace(/<\//g, '<\\/')}<\/script>`
	);

	let { children } = $props();

	const webManifestLink = $derived(pwaInfo?.webManifest.linkTag ?? '');

	// Las páginas /legal/* son documentos de referencia, no pantallas de la
	// app: el selector de ciudad y la barra de pestañas móvil (que además
	// puede tapar el final del texto en pantallas pequeñas) no aportan nada
	// ahí y sí distraen. LegalPageShell ya pone su propio "Volver a Convoca".
	const isLegalRoute = $derived(page.url.pathname.startsWith('/legal'));

	/**
	 * `import()` dinámico en vez de estático, guardado por el mismo `if
	 * (ENABLE_DEV_TOOLS)`: con un import estático, Svelte compila el `{#if}`
	 * como una rama en tiempo de EJECUCIÓN — el componente (con su texto
	 * "Reset local (dev)") queda igualmente en el bundle que descarga
	 * cualquier visitante de staging/producción, aunque nunca se monte.
	 * Verificado en vivo con un build real (`grep` del output): con import
	 * estático, la cadena aparecía en el bundle del layout raíz incluso con
	 * `PUBLIC_ENABLE_DEV_TOOLS=false`. Con `import()` dinámico, Rollup lo
	 * separa en un chunk aparte que solo se solicita si este código llega a
	 * ejecutarse — y no se ejecuta cuando `ENABLE_DEV_TOOLS` es `false`.
	 */
	let DevResetButton = $state<Component | null>(null);
	if (ENABLE_DEV_TOOLS) {
		import('$lib/components/dev/DevResetButton.svelte').then((m) => {
			DevResetButton = m.default;
		});
	}
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
	<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
	<meta name="theme-color" content="#176056" />
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- trusted markup generated by @vite-pwa/sveltekit at build time, not user input. -->
	{@html webManifestLink}
	{#each siteJsonLdBlocks as block (block)}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- JSON-LD fijo generado por organizationJsonLd()/websiteJsonLd(), sin datos de usuario. -->
		{@html block}
	{/each}
</svelte:head>

<div class="flex min-h-dvh flex-col bg-ink-50">
	<TopBar minimal={isLegalRoute} />
	<main class="flex-1 {isLegalRoute ? '' : 'pb-20 md:pb-0'}">
		{@render children()}
		<Footer />
	</main>
	{#if !isLegalRoute}
		<MobileTabBar />
	{/if}
	{#if DevResetButton}
		<DevResetButton />
	{/if}
</div>
