<script lang="ts">
	import './layout.css';
	import favicon from '$lib/assets/favicon.svg';
	import TopBar from '$lib/components/nav/TopBar.svelte';
	import MobileTabBar from '$lib/components/nav/MobileTabBar.svelte';
	import DevResetButton from '$lib/components/dev/DevResetButton.svelte';
	import { pwaInfo } from 'virtual:pwa-info';

	let { children } = $props();

	const webManifestLink = $derived(pwaInfo?.webManifest.linkTag ?? '');
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
	<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
	<meta name="theme-color" content="#176056" />
	<meta
		name="description"
		content="Convoca: descubre, verifica y confirma tu asistencia a concentraciones y movilizaciones ciudadanas legales y pacíficas, sin exponer tu identidad."
	/>
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- trusted markup generated by @vite-pwa/sveltekit at build time, not user input. -->
	{@html webManifestLink}
</svelte:head>

<div class="flex min-h-dvh flex-col bg-ink-50">
	<TopBar />
	<main class="flex-1 pb-20 md:pb-0">
		{@render children()}
	</main>
	<MobileTabBar />
	{#if import.meta.env.DEV}
		<DevResetButton />
	{/if}
</div>
