<script lang="ts">
	import './layout.css';
	import favicon from '$lib/assets/favicon.svg';
	import TopBar from '$lib/components/nav/TopBar.svelte';
	import MobileTabBar from '$lib/components/nav/MobileTabBar.svelte';
	import { ENABLE_DEV_TOOLS } from '$lib/config/env';
	import { pwaInfo } from 'virtual:pwa-info';
	import type { Component } from 'svelte';

	let { children } = $props();

	const webManifestLink = $derived(pwaInfo?.webManifest.linkTag ?? '');

	/**
	 * `import()` dinámico en vez de estático, guardado por el mismo `if
	 * (ENABLE_DEV_TOOLS)`: con un import estático, Svelte compila el `{#if}`
	 * como una rama en tiempo de EJECUCIÓN — el componente (con su texto
	 * "Reset local (dev)") queda igualmente en el bundle que descarga
	 * cualquier visitante de staging/producción, aunque nunca se monte.
	 * Verificado en vivo con un build real (`grep` del output): con import
	 * estático, la cadena aparecía en el bundle del layout raíz incluso con
	 * `PUBLIC_ENABLE_DEV_TOOLS=false`. Con `import()` dinámico, Rollup lo
	 * separa en un chunk aparte que solo se solicita si este código llega a
	 * ejecutarse — y no se ejecuta cuando `ENABLE_DEV_TOOLS` es `false`.
	 */
	let DevResetButton = $state<Component | null>(null);
	if (ENABLE_DEV_TOOLS) {
		import('$lib/components/dev/DevResetButton.svelte').then((m) => {
			DevResetButton = m.default;
		});
	}
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
	<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
	<meta name="theme-color" content="#176056" />
	<meta
		name="description"
		content="Convoca: descubre, verifica y confirma tu asistencia a concentraciones y movilizaciones ciudadanas legales y pacíficas, sin exponer tu identidad."
	/>
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- trusted markup generated by @vite-pwa/sveltekit at build time, not user input. -->
	{@html webManifestLink}
</svelte:head>

<div class="flex min-h-dvh flex-col bg-ink-50">
	<TopBar />
	<main class="flex-1 pb-20 md:pb-0">
		{@render children()}
	</main>
	<MobileTabBar />
	{#if DevResetButton}
		<DevResetButton />
	{/if}
</div>
